{
 "title": "Kubernetes Cluster Resources",
 "description": "Display usage of resources by namespaces in kubernetes cluster.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "Cluster", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "(CPU) Allocated Requests by Namespace",
   "type": "grafana-piechart-panel",
   "description": "100% is the sum of all allocated CPU Requests.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum by (namespace) (kube_resourcequota{resource=\"requests.cpu\",type=\"hard\"}))"
    }
   ]
  },
  {
   "title": "(CPU) Allocated Limits by Namespace",
   "type": "grafana-piechart-panel",
   "description": "100% is the sum of all allocated CPU Limits.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum by (namespace) (kube_resourcequota{resource=\"limits.cpu\",type=\"hard\"}))"
    }
   ]
  },
  {
   "title": "(RAM) Allocated Requests by Namespace",
   "type": "grafana-piechart-panel",
   "description": "100% is the sum of all allocated Memory Requests.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum by (namespace) (kube_resourcequota{resource=\"requests.memory\",type=\"hard\"}))"
    }
   ]
  },
  {
   "title": "(RAM) Allocated Limits by Namespace",
   "type": "grafana-piechart-panel",
   "description": "100% is the sum of all allocated Memory Limits.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum by (namespace) (kube_resourcequota{resource=\"limits.memory\",type=\"hard\"}))"
    }
   ]
  },
  {
   "title": "(CPU) Namespaces Limits Quota / Cluster Resources",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (kube_resourcequota{resource=\"limits.cpu\",type=\"hard\"}) / sum(kube_node_status_allocatable_cpu_cores{node!~\"kubemaster.*\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "(CPU) Namespaces Requests Quota  /  Cluster Resources",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"hard\"}) / sum(kube_node_status_allocatable_cpu_cores{node!~\"kubemaster.*\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "(CPU) All Pods Requests  /  Cluster Resources",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (kube_pod_container_resource_requests_cpu_cores{}) / sum(kube_node_status_allocatable_cpu_cores{node!~\"kubemaster.*\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "(CPU) Actual Usage / Cluster Resources",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\"}[1m])) / sum(kube_node_status_allocatable_cpu_cores{node!~\"kubemaster.*\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "(RAM) Namespaces Limits Quota / Cluster Resources",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(kube_resourcequota{resource=\"limits.memory\",type=\"hard\"}) / sum(kube_node_status_allocatable_memory_bytes{node!~\"kubemaster.*\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "(RAM) Namespaces Requests Quota / Cluster Resources",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(kube_resourcequota{resource=\"requests.memory\",type=\"hard\"}) / sum(kube_node_status_allocatable_memory_bytes{node!~\"kubemaster.*\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "(RAM) All Pods Reqests  /  Cluster Resources",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (kube_pod_container_resource_requests_memory_bytes) / sum(kube_node_status_allocatable_memory_bytes{node!~\"kubemaster.*\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "(RAM) Actual Usage  /  Cluster Resources",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\"}) / sum(kube_node_status_allocatable_memory_bytes{node!~\"kubemaster.*\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node!~\"kubemaster.*\"})",
     "legendFormat": "CPU All Allocable Resources"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\"}[1m]))",
     "legendFormat": "CPU Actual Usage"
    },
    {
     "expr": "sum (kube_resourcequota{resource=\"limits.cpu\", type=\"hard\"})",
     "legendFormat": "CPU Quota Limits"
    },
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.cpu\", type=\"hard\"})",
     "legendFormat": "CPU Quota Requests"
    },
    {
     "expr": "sum(kube_resourcequota{resource=\"limits.cpu\", type=\"used\"})",
     "legendFormat": "CPU  Used Limits"
    },
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.cpu\", type=\"used\"})",
     "legendFormat": "CPU Used Requests"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node!~\"kubemaster.*\"})",
     "legendFormat": "Memory All Allocable Resources"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\"})",
     "legendFormat": "Memory Actual Usage"
    },
    {
     "expr": "sum(kube_resourcequota{resource=\"limits.memory\", type=\"hard\"})",
     "legendFormat": "Memory Quota Limits"
    },
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.memory\", type=\"hard\"})",
     "legendFormat": "Memory Quota Requests"
    },
    {
     "expr": "sum(kube_resourcequota{resource=\"limits.memory\", type=\"used\"})",
     "legendFormat": "Memory Used Limits"
    },
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.memory\", type=\"used\"})",
     "legendFormat": "Memory Used Requests"
    }
   ]
  },
  {
   "title": "Pods Count / Pods quota",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 29 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(kubelet_running_pod_count) / sum(kube_node_status_allocatable_pods) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pods per node",
   "type": "graph",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "avg(kube_node_status_allocatable_pods)",
     "legendFormat": "Max Pods Per Node"
    },
    {
     "expr": "sort_desc(sum by (instance) (kubelet_running_pod_count))",
     "legendFormat": "Pods count {{instance}}"
    }
   ]
  }
 ]
}